version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bargain-notifier-api-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1krlrx1pq928q"
s3_prefix = "bargain-notifier-api-prod"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
